name: "游 Bug report"
description: Nahl치sit chybu nebo probl칠m
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        D칤ky, 쬰 hl치s칤te bug! Pros칤m vypl켿te n치sleduj칤c칤 informace.
  - type: textarea
    id: what-happened
    attributes:
      label: Co se stalo?
      description: Popi코te, co se pokazilo a co jste o캜ek치vali.
      placeholder: "Po kliknut칤 na tla캜칤tko X se nestalo nic..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Kroky k reprodukci
      description: Jak chybu zopakovat?
      placeholder: |
        1. Otev콏i str치nku ...
        2. Klikni na ...
        3. O캜ek치val jsem ...
        4. Ale m칤sto toho ...
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshoty / logy
      description: P콏ilo screenshot nebo log, pokud je to mo쬹칠.
  - type: input
    id: environment
    attributes:
      label: Prost콏ed칤
      description: Nap콏. OS, prohl칤쬰캜, verze aplikace...
      placeholder: "Windows 11, Firefox 118"
