name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install deps
        working-directory: holly-2.0/apps/web
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            npm ci
          else
            npm install
          fi

      - name: Build web
        working-directory: holly-2.0/apps/web
        run: npm run build

      - name: Upload web dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: holly-2.0/apps/web/dist

      - name: Locate dist path
        id: find_dist
        shell: bash
        run: |
          set -e
          CANDIDATES=("apps/web/dist" "web/dist" "packages/web/dist" "frontend/dist" "dist")
          for p in "${CANDIDATES[@]}"; do
            if [ -d "$p" ] && [ -n "$(ls -A "$p")" ]; then
              echo "Found dist at: $p"
              echo "path=$p" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done
          echo "No dist folder found in candidates: ${CANDIDATES[*]}" >&2
          echo "Workspace layout:"
          ls -la
          exit 1

      - name: Upload web dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: ${{ steps.find_dist.outputs.path }}
          if-no-files-found: error

  android-twa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'false'
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Gradle wrapper
        run: test -f android-twa/Holly2_TWA_Skeleton/gradlew

      - name: Build Android TWA (debug)
        run: cd android-twa/Holly2_TWA_Skeleton && ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android-twa/Holly2_TWA_Skeleton/app/build/outputs/apk/debug/*.apk
