name: CI (npm, workspaces)

on:
  push:
    branches: [main]
    paths:
      - "apps/**"
      - "packages/**"
      - "config/**"
      - "scripts/**"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Verify lockfile exists
        run: |
          if [ ! -f package-lock.json ]; then
            echo "::error::package-lock.json chybí. Spusť lokálně 'npm install' a commitni lockfile."
            exit 1
          fi

      - name: Install deps (ci)
        run: npm ci

      - name: Build web
        run: npm -w @holly/web run build

      - name: Build server
        run: npm -w @holly/server run build

      - name: Test (if present)
        run: npm test --workspaces --if-present

      - name: Upload web dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
          if-no-files-found: error
          retention-days: 7

      - name: Upload server dist
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: apps/server/dist
          if-no-files-found: ignore
          retention-days: 7