name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build web
        run: npm -w @holly/web run build

      - name: Upload web dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist

  android-twa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Gradle wrapper
        run: test -f android-twa/Holly2_TWA_Skeleton/gradlew

      - name: Build Android TWA (debug)
        run: cd android-twa/Holly2_TWA_Skeleton && ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android-twa/Holly2_TWA_Skeleton/app/build/outputs/apk/debug/*.apk
