name: CI (npm, workspaces)

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Pokud máš v repu package-lock.json, použij ci pro čistou instalaci
      - name: Install deps
        run: npm ci

      # Postavíme web i server přes workspace příkazy
      - name: Build web
        run: npm -w @holly/web run build

      - name: Build server
        run: npm -w @holly/server run build

      # Spusť testy, pokud v některém workspace existují (necháme "if-present")
      - name: Test (if present)
        run: npm test --workspaces --if-present

      # Artefakty z buildu – uprav cesty podle projektu
      - name: Upload web dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
          if-no-files-found: ignore

      - name: Upload server dist
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: apps/server/dist
          if-no-files-found: ignore
