name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build web (workspace with fallbacks)
        run: |
          set -e
          npm -w @holly/web run build || {
            echo "Workspace build failed or workspace not found, trying fallbacks..."
            if [ -d "apps/web" ]; then (cd apps/web && npm ci && npm run build); \
            elif [ -d "web" ]; then (cd web && npm ci && npm run build); \
            elif [ -d "packages/web" ]; then (cd packages/web && npm ci && npm run build); \
            else echo "No known web directory found"; exit 1; fi
          }

      - name: Locate dist path
        id: find_dist
        shell: bash
        run: |
          set -e
          CANDIDATES=("apps/web/dist" "web/dist" "packages/web/dist" "frontend/dist" "dist")
          for p in "${CANDIDATES[@]}"; do
            if [ -d "$p" ] && [ -n "$(ls -A "$p")" ]; then
              echo "Found dist at: $p"
              echo "path=$p" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done
          echo "No dist folder found in candidates: ${CANDIDATES[*]}" >&2
          echo "Workspace layout:"
          ls -la
          exit 1

      - name: Upload web dist
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: ${{ steps.find_dist.outputs.path }}
          if-no-files-found: error

  android-twa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Gradle wrapper
        run: test -f android-twa/Holly2_TWA_Skeleton/gradlew

      - name: Build Android TWA (debug)
        run: cd android-twa/Holly2_TWA_Skeleton && ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android-twa/Holly2_TWA_Skeleton/app/build/outputs/apk/debug/*.apk
