name: Release Builder

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify APK exists
        run: |
          test -f Holly_2.0_Pro.apk || (echo "APK not found (Holly_2.0_Pro.apk v rootu repa)" && exit 1)
          ls -lh Holly_2.0_Pro.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Holly 2.0 Pro v${{ github.run_number }}"
          body: |
            **Nové vydání Holly 2.0 Pro**
            - Automatické nahrání APK
            - Build ID: ${{ github.run_number }}
            - Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK asset
        uses: softprops/action-gh-release@v2
        with:
          files: Holly_2.0_Pro.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
